from __future__ import annotations

import re
from typing import List

from ..models import EvidenceItem, Fault
from ..prompts import DELTA_PATCH_PROMPT, EXECUTOR_PROMPT
from ..services.llm_client import LLMClient


class ExecutorAgent:
    """Generate drafts and apply targeted revisions.

    What:
        Produces initial outputs and delta patches from reviewer faults.
    Why:
        Keeps execution concerns separate so iterative refinement remains controllable.
    """

    def __init__(self, llm: LLMClient) -> None:
        """Initialize executor dependencies.

        What:
            Stores the LLM client used for generation and patch prompts.
        Why:
            Maintains a single model-access abstraction across the pipeline.
        """
        self.llm = llm

    @staticmethod
    def _canonical_section(title: str) -> str | None:
        """Map heading text to one of the required canonical section names.

        What:
            Normalizes section heading variants into stable canonical buckets.
        Why:
            Supports deterministic section reordering despite small model phrasing drift.
        """
        value = title.strip().lower()
        value = value.replace("&", " and ")
        value = re.sub(r"[^a-z0-9\s]", " ", value)
        value = re.sub(r"\s+", " ", value).strip()

        if "sample" in value and "output" in value:
            return "Sample Output"
        if "analysis" in value:
            return "Analysis"
        if "rule" in value and "constraint" in value:
            return "Rules and Constraints"
        if "contingenc" in value:
            return "Contingencies"
        if "assumption" in value:
            return "Assumptions"
        return None

    def _enforce_markdown_structure(self, text: str) -> str:
        """Reorder markdown sections into required deterministic structure.

        What:
            Extracts known top-level sections and rewrites them in the target order.
        Why:
            Guarantees a stable response layout even when model output drifts.
        """
        if not text.strip():
            return text

        heading_re = re.compile(r"^(#{1,2})\s+(.+?)\s*$", re.MULTILINE)
        matches = list(heading_re.finditer(text))
        if not matches:
            return text

        preface = text[: matches[0].start()].strip()
        required_order = [
            "Sample Output",
            "Analysis",
            "Rules and Constraints",
            "Contingencies",
            "Assumptions",
        ]

        section_content: dict[str, str] = {}
        extras: list[str] = []

        for index, match in enumerate(matches):
            raw_title = match.group(2).strip()
            start = match.end()
            end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
            body = text[start:end].strip()
            canonical = self._canonical_section(raw_title)

            if canonical and canonical not in section_content:
                section_content[canonical] = body
            else:
                extras.append(f"## {raw_title}\n\n{body}".strip())

        if preface:
            if section_content.get("Analysis"):
                section_content["Analysis"] = f"{preface}\n\n{section_content['Analysis']}".strip()
            else:
                section_content["Analysis"] = preface

        parts: list[str] = []
        for name in required_order:
            content = section_content.get(name, "_Not generated by model in this pass._")
            parts.append(f"## {name}\n\n{content}".strip())

        if extras:
            parts.append("## Additional Notes\n\n" + "\n\n".join(extras))

        return "\n\n".join(parts).strip()

    def generate(
        self,
        goal: str,
        constraints: List[str],
        output_format: str,
        plan_summary: str,
        subtasks: List[str],
        evidence: List[EvidenceItem],
    ) -> str:
        """Generate the first complete draft.

        What:
            Synthesizes goal, constraints, plan details, and evidence into one output.
        Why:
            Creates a concrete artifact for the review/patch loop to improve iteratively.
        """
        prompt = (
            f"Goal:\n{goal}\n\n"
            f"Output format: {output_format}\n\n"
            f"Constraints:\n- " + "\n- ".join(constraints if constraints else ["None provided"]) + "\n\n"
            f"Plan summary:\n{plan_summary}\n\n"
            f"Subtasks:\n- " + "\n- ".join(subtasks if subtasks else ["None"]) + "\n\n"
            f"Evidence:\n" + "\n".join([f"- {item.title}: {item.snippet} ({item.url})" for item in evidence[:10]]) + "\n\n"
            "Return sections in this exact order: "
            "Sample Output, Analysis, Rules and Constraints, Contingencies, Assumptions. "
            "The first section must be a concrete sample deliverable that follows the stated constraints."
        )
        raw = self.llm.complete_text(EXECUTOR_PROMPT, prompt)
        return self._enforce_markdown_structure(raw)

    def patch(self, draft: str, faults: List[Fault]) -> str:
        """Patch an existing draft using reviewer fault instructions.

        What:
            Applies issue-specific fixes rather than recreating the whole draft.
        Why:
            Delta patching is cheaper and often more stable than full regeneration.
        """
        fault_text = "\n".join(
            [f"- [{fault.severity}] {fault.issue} | Patch: {fault.patch_instruction}" for fault in faults]
        )
        prompt = f"Current draft:\n{draft}\n\nFaults:\n{fault_text}\n"
        raw = self.llm.complete_text(DELTA_PATCH_PROMPT, prompt)
        return self._enforce_markdown_structure(raw)
